name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/artemserebrennikov/buildozer:latest
      options: --user root

    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        run: |
          buildozer -v android debug
          ls -l bin/*.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
